cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update/<int:product_id>/', views.update_cart, name='update_cart'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth import views as auth_views  # Import Django's auth views
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
	# customer home
	path('', include('home.urls')),


	path('accounts/', include('accounts.urls')),
	# path('accounts/', include('allauth.urls')),
	path('dashboard/', include('accounts.urls')),
	path('products/', include('products.urls')),
    path('customers/', include('users.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('cart/', include('cart.urls')),
	
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import product_list, product_list_admin, add_product, edit_product, delete_product, product_details, category_list, add_category, category_details, edit_category, delete_category

urlpatterns = [
	# product
    path('', product_list, name='product_list'),  # Public product list
	path('products-list', product_list_admin, name='products-list-admin'), # Admin only
    path('add/', add_product, name='add_product'),  # Admin only
	path('<int:product_id>/', product_details, name='product_details'), # customer view
	# path('<int:product_id>/', product_details, name='product_view'), # admin view
    path('edit/<int:product_id>', edit_product, name='edit_product'),  # Admin only
    path('delete/<int:product_id>', delete_product, name='delete_product'),  # Admin only
	
	# product category
    path('categories-list', category_list, name='categories-list'), # Admin only
    path('categories/add-category/', add_category, name='add_category'),  # Admin only
	path('categories/<int:category_id>/', category_details, name='category_details'),
    path('categories/edit/<int:category_id>/', edit_category, name='edit_category'),  # Admin only
    path('categories/delete/<int:category_id>/', delete_category, name='delete_category'),  # Admin only
]

products/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(upload_to='products/')  # Make sure media files are handled
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .models import Product, Category

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category', 'price', 'description', 'image', 'published']



class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

products/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import Product
from .forms import ProductForm
from .models import Category
from .forms import CategoryForm

# View for listing products (accessible to all users)
def product_list(request):
    # products = Product.objects.all()
    # Filter products to only show published ones
    products = Product.objects.filter(published=True)
    categories = Category.objects.all()
    return render(request, 'products/product_list.html', {'products': products, 'categories': categories})
    # return HttpResponse('Hello')

# View for listing products (admin/staff users)
@staff_member_required
def product_list_admin(request):
    products = Product.objects.all()
    return render(request, 'products/product_list_admin.html', {'products': products})
    # return HttpResponse('Hello')

# Only admin users can add a product
@staff_member_required
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('products-list-admin')
    else:
        form = ProductForm()
    return render(request, 'products/product_add.html', {'form': form})


# products details view for customers
def product_details(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated and request.user.is_staff:
        return render(request, 'products/product_view.html', {'product': product})
    else:
        categories = Category.objects.all()
        return render(request, 'products/product_details.html', {'product': product, 'categories': categories})
    # if request.method == 'POST':
    #     form = ProductForm(request.POST, request.FILES, instance=product)
    #     if form.is_valid():
    #         form.save()
    #         return redirect('product_list')
    # else:
    #     form = ProductForm(instance=product)
    


# Only admin users can update a product
# @staff_member_required
# def product_view(request, product_id):
#     product = get_object_or_404(Product, id=product_id)
#     return render(request,)


# Only admin users can update a product
@staff_member_required
def edit_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products-list-admin')
    else:
        form = ProductForm(instance=product)
    return render(request, 'products/product_edit.html', {'form': form})

# Only admin users can delete a product
@staff_member_required
def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        product.delete()
        return redirect('products-list-admin')
    return render(request, 'products/product_confirm_delete.html', {'product': product})


# Product category
# View for listing products (accessible to all users)
@staff_member_required
def category_list(request):
    categories = Category.objects.all()
    return render(request, 'products/category_list.html', {'categories': categories})
    # return HttpResponse('Hello')

# Only admin users can add a product
@staff_member_required
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('categories-list')
    else:
        form = CategoryForm()
    return render(request, 'products/category_add.html', {'form': form})


# Only admin users can update a product
# @staff_member_required
def category_details(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    return render(request, 'products/category_view.html', {'category': category}) # {'category': category})


# Only admin users can update a product
@staff_member_required
def edit_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            print('valid form')
            form.save()
            return redirect('categories-list')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'products/category_edit.html', {'form': form})

# Only admin users can delete a product
@staff_member_required
def delete_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    if request.method == 'POST':
        category.delete()
        messages.success(request, 'Category deleted successfully!')
        return redirect('categories-list')
    # return render(request, 'products/category_confirm_delete.html', {'category': category})

products/templates/products/category_add.html
{% extends "base_admin.html" %}

{% load static %}
{% block title %} Add Product {% endblock %}

{% block content %}
<nav class="mb-3" aria-label="breadcrumb">
	<ol class="breadcrumb mb-0">
		<li class="breadcrumb-item"><a href="{% url 'staff_dashboard' %}">Dashboard</a></li>
		<li class="breadcrumb-item"><a href="{% url 'products-list-admin' %}">Products</a></li>
		<li class="breadcrumb-item"><a href="{% url 'category-list' %}">Products Categories</a></li>
		<li class="breadcrumb-item active">Add New Product Category</li>
	</ol>
</nav>
<form class="mb-9">
	<div class="row g-3 flex-between-end mb-5">
		<div class="col-auto">
			<h2 class="mb-2">Add a product category</h2>
		</div>
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-name">Name</label>
		<input class="form-control" id="basic-form-name" type="text" placeholder="Name" />
	</div>
	<a class="btn btn-warning" href="{% url 'category-list' %}">Cancel</a>
	<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

products/templates/products/category_edit.html
{% extends "base_admin.html" %}

{% load static %}
{% block title %} Add Product {% endblock %}

{% block content %}
<nav class="mb-3" aria-label="breadcrumb">
	<ol class="breadcrumb mb-0">
		<li class="breadcrumb-item"><a href="{% url 'staff_dashboard' %}">Dashboard</a></li>
		<li class="breadcrumb-item"><a href="{% url 'products-list-admin' %}">Products</a></li>
		<li class="breadcrumb-item"><a href="{% url 'categories-list' %}">Products Categories</a></li>
		<li class="breadcrumb-item active">Edit Product Category</li>
	</ol>
</nav>
<form class="mb-9" method="POST">
	{% csrf_token %}
	<div class="row g-3 flex-between-end mb-5">
		<div class="col-auto">
			<h2 class="mb-2">Edit product category</h2>
		</div>
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-name">Name</label>
		<input class="form-control" name="name" id="id_name" type="text" value="{{ form.name.value|default_if_none:'' }}" placeholder="Name" />
		{% if form.name.errors %}
		<div class="text-danger fs-9">
			{% for error in form.name.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<a class="btn btn-warning" href="{% url 'categories-list' %}">Cancel</a>
	<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

products/templates/products/category_list.html
{% extends "base_admin.html" %}

{% load static %}
{% block title %} Products {% endblock  %}

{% block content %}
<nav class="mb-3" aria-label="breadcrumb">
	<ol class="breadcrumb mb-0">
		<li class="breadcrumb-item"><a href="{% url 'staff_dashboard' %}">Dashboard</a></li>
		<li class="breadcrumb-item"><a href="{% url 'products-list-admin' %}">Products</a></li>
		<li class="breadcrumb-item active">Products Category</li>
	</ol>
</nav>
<div class="mb-9">
	<div id="products-category" data-list=''>
		<div class="mb-4">
			<div class="d-flex flex-wrap gap-3">
				<div class="ms-xxl-auto">
					<button class="btn btn-link text-body me-4 px-0"><span class="fa-solid fa-file-export fs-9 me-2"></span>Export</button>
					<a class="btn btn-primary" id="addBtn" href="{% url 'add_category' %}"><span class="fas fa-plus me-2"></span>Add product category</a>
				</div>
			</div>
		</div>
		<div id="tableExample3" data-list='{"valueNames":["name","email","age"],"page":5,"pagination":true}'>
			<div class="search-box mb-3 mx-auto">
				<form class="position-relative"><input class="form-control search-input search form-control-sm" type="search"
						placeholder="Search" aria-label="Search" />
					<span class="fas fa-search search-box-icon"></span>
				</form>
			</div>
			<div class="table-responsive">
				<table class="table table-striped table-sm fs-9 mb-0">
					<thead>
						<tr>
							<th class="sort border-top border-translucent ps-3" data-sort="name">Name</th>
							<th class="sort text-end align-middle pe-0 border-top" scope="col">ACTION</th>
						</tr>
					</thead>
					<tbody class="list">
						{% for category in categories %}
						<tr>
							<td class="align-middle ps-3 name">{{ category.name }}</td>
							<td class="align-middle white-space-nowrap text-end pe-0">
								<div class="btn-reveal-trigger position-static">
									<button
										class="btn btn-sm dropdown-toggle dropdown-caret-none transition-none btn-reveal fs-10" type="button"
										data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true" aria-expanded="false"
										data-bs-reference="parent"><span class="fas fa-ellipsis-h fs-10"></span>
									</button>
									<div class="dropdown-menu dropdown-menu-end py-2">
										<a class="dropdown-item" href="{% url 'category_details' category.id %}">View</a>
										<a class="dropdown-item" href="{% url 'edit_category' category.id %}">Edit</a>
										<div class="dropdown-divider"></div>
										<form action="{% url 'delete_category' category.id %}" method="post">
											{% csrf_token %}
											<button class="dropdown-item text-danger" type="submit" onclick="return confirm('Are you sure you want to delete this category?')">Remove</button>
										</form>
										
									</div>
								</div>
							</td>
						</tr>
						{% endfor %}
						
					</tbody>
				</table>
			</div>
			<div class="d-flex flex-between-center pt-3">
				<div class="pagination d-none"></div>
				<p class="mb-0 fs-9">
					<span class="d-none d-sm-inline-block" data-list-info="data-list-info"></span>
					<span class="d-none d-sm-inline-block"> &mdash; </span>
					<a class="fw-semibold" href="#!" data-list-view="*">
						View all <span class="fas fa-angle-right ms-1" data-fa-transform="down-1"></span>
					</a>
					<a class="fw-semibold d-none" href="#!" data-list-view="less">
						View Less <span class="fas fa-angle-right ms-1" data-fa-transform="down-1"></span>
					</a>
				</p>
				<div class="d-flex">
					<button class="btn btn-sm btn-primary" type="button" data-list-pagination="prev"><span>Previous</span></button>
					<button class="btn btn-sm btn-primary px-4 ms-2" type="button" data-list-pagination="next"><span>Next</span></button>
				</div>
			</div>
		</div>	
	</div>
</div>
{% endblock %}

products/templates/products/category_view.html
{% extends "base_admin.html" %}

{% load static %}
{% block title %} Add Product {% endblock %}

{% block content %}
<nav class="mb-3" aria-label="breadcrumb">
	<ol class="breadcrumb mb-0">
		<li class="breadcrumb-item"><a href="{% url 'staff_dashboard' %}">Dashboard</a></li>
		<li class="breadcrumb-item"><a href="{% url 'products-list-admin' %}">Products</a></li>
		<li class="breadcrumb-item"><a href="{% url 'categories-list' %}">Products Categories</a></li>
		<li class="breadcrumb-item active">Category details</li>
	</ol>
</nav>
<!-- <form class="mb-9" method="POST">
	{% csrf_token %} -->
	<div class="row g-3 flex-between-end mb-5">
		<div class="col-auto">
			<h2 class="mb-2">Category details</h2>
		</div>
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-name">Name</label>
		<input class="form-control" name="name" id="id_name" type="text" value="{{ category.name|default_if_none:'' }}" placeholder="Name" disabled/>
	</div>
	<a class="btn btn-warning" href="{% url 'categories-list' %}">Cancel</a>
	<a class="btn btn-primary" href="{% url 'edit_category' category.id %}" type="submit">Edit</a>
<!-- </form> -->
{% endblock %}

products/templates/products/product_add.html
{% extends "base_admin.html" %}

{% load static %}
{% block title %} Add Product {% endblock %}

{% block content %}
<nav class="mb-3" aria-label="breadcrumb">
	<ol class="breadcrumb mb-0">
		<li class="breadcrumb-item"><a href="{% url 'staff_dashboard' %}">Dashboard</a></li>
		<li class="breadcrumb-item"><a href="{% url 'products-list-admin' %}">Products</a></li>
		<li class="breadcrumb-item active">Add New Product</li>
	</ol>
</nav>
<form class="mb-9" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="row g-3 flex-between-end mb-5">
		<div class="col-auto">
			<h2 class="mb-2">Add a product</h2>
		</div>
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-name">Product Name</label>
		<input class="form-control" name="name" maxlength="200"  id="id_name" type="text" value="{{ form.name.value|default_if_none:'' }}" placeholder="Product name" />
		{% if form.name.errors %}
		<div class="text-danger fs-9">
			{% for error in form.name.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-gender">Category</label>
		<select class="form-select" name="category"  id="id_category" aria-label="Default select example">
			<option selected="selected">Select product category</option>
			{% for category in form.category.field.queryset %}
			<option value="{{ category.pk }}" {% if form.category.value == category.pk %}selected{% endif %}>{{ category.name }}</option>
			{% endfor %}
			<!-- <option value="male">Male</option>
			<option value="female">Female</option>
			<option value="other">Other</option> -->
		</select>
		{% if form.category.errors %}
		<div class="text-danger fs-9">
			{% for error in form.category.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-password">Price</label>
		<input class="form-control" name="price" step="0.01"  id="id_price" type="number" value="{{ form.price.value|default_if_none:'' }}" placeholder="$" />
		{% if form.price.errors %}
		<div class="text-danger fs-9">
			{% for error in form.price.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<div class="mb-3">
		<label class="form-label">Product Image</label>
		<input class="form-control" type="file" name="image" accept="image/*" id="id_image" />
		{% if form.image.errors %}
		<div class="text-danger fs-9">
			{% for error in form.image.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-textarea">Description</label>
		<textarea class="form-control" name="description" id="basic-form-textarea" rows="5" cols="40" placeholder="Description">{{ form.description.value|default_if_none:'' }}</textarea>
		{% if form.description.errors %}
		<div class="text-danger fs-9">
			{% for error in form.description.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<div class="mb-3 form-check">
		<input class="form-check-input" name="published" id="id_published" {% if form.published.value %}checked{% endif %} type="checkbox" />
		<label class="form-check-label" for="basic-form-checkbox">Publish Product</label>
		{% if form.published.errors %}
		<div class="text-danger fs-9">
			{% for error in form.published.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<div class="col-auto">
		<a class="btn btn-warning me-2 mb-2 mb-sm-0" href="{% url 'products-list-admin' %}">Cancel</a>
		<button class="btn btn-primary me-2 mb-2 mb-sm-0" type="submit">Save</button>
	</div>
	<!-- <button class="btn btn-primary" type="submit">Submit</button> -->


	
</form>
{% endblock %}

products/templates/products/product_edit.html
{% extends "base_admin.html" %}

{% load static %}
{% block title %} Add Product {% endblock %}

{% block content %}
<nav class="mb-3" aria-label="breadcrumb">
	<ol class="breadcrumb mb-0">
		<li class="breadcrumb-item"><a href="{% url 'staff_dashboard' %}">Dashboard</a></li>
		<li class="breadcrumb-item"><a href="{% url 'products-list-admin' %}">Products</a></li>
		<li class="breadcrumb-item active">Edit Product</li>
	</ol>
</nav>
<form class="mb-9" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="row g-3 flex-between-end mb-5">
		<div class="col-auto">
			<h2 class="mb-2">Edit product</h2>
		</div>
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-name">Product Name</label>
		<input class="form-control" name="name" maxlength="200"  id="id_name" type="text" value="{{ form.name.value|default_if_none:'' }}" placeholder="Product name" />
		{% if form.name.errors %}
		<div class="text-danger fs-9">
			{% for error in form.name.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-gender">Category</label>
		<select class="form-select" name="category"  id="id_category" aria-label="Default select example">
			<option selected="selected">Select product category</option>
			{% for category in form.category.field.queryset %}
			<option value="{{ category.pk }}" {% if form.category.value == category.pk %}selected{% endif %}>{{ category.name }}</option>
			{% endfor %}
		</select>
		{% if form.category.errors %}
		<div class="text-danger fs-9">
			{% for error in form.category.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-password">Price</label>
		<input class="form-control" name="price" step="0.01"  id="id_price" type="number" value="{{ form.price.value|default_if_none:'' }}" placeholder="$" />
		{% if form.price.errors %}
		<div class="text-danger fs-9">
			{% for error in form.price.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<div class="mb-3">
		<label class="form-label">Product Image</label>
		<input class="form-control" type="file" name="image" accept="image/*" id="id_image" />
		{% if form.image.errors %}
		<div class="text-danger fs-9">
			{% for error in form.image.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-textarea">Description</label>
		<textarea class="form-control" name="description" id="basic-form-textarea" rows="5" cols="40" placeholder="Description">{{ form.description.value|default_if_none:'' }}</textarea>
		{% if form.description.errors %}
		<div class="text-danger fs-9">
			{% for error in form.description.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<div class="mb-3 form-check">
		<input class="form-check-input" name="published" id="id_published" {% if form.published.value %}checked{% endif %} type="checkbox" />
		<label class="form-check-label" for="basic-form-checkbox">Publish Product</label>
		{% if form.published.errors %}
		<div class="text-danger fs-9">
			{% for error in form.published.errors %}
			<p>{{ error }}</p>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	<div class="col-auto">
		<a class="btn btn-warning me-2 mb-2 mb-sm-0" href="{% url 'products-list-admin' %}">Cancel</a>
		<button class="btn btn-primary me-2 mb-2 mb-sm-0" type="submit">Save</button>
	</div>
	<!-- <button class="btn btn-primary" type="submit">Submit</button> -->


	
</form>
{% endblock %}

products/templates/products/product_view.html
{% extends "base_admin.html" %}

{% load static %}
{% block title %} Add Product {% endblock %}

{% block content %}
<nav class="mb-3" aria-label="breadcrumb">
	<ol class="breadcrumb mb-0">
		<li class="breadcrumb-item"><a href="{% url 'staff_dashboard' %}">Dashboard</a></li>
		<li class="breadcrumb-item"><a href="{% url 'products-list-admin' %}">Products</a></li>
		<li class="breadcrumb-item active">Product details</li>
	</ol>
</nav>
<!-- <form class="mb-9" method="POST" enctype="multipart/form-data"> -->
	<!-- {% csrf_token %} -->
	<div class="row g-3 flex-between-end mb-5">
		<div class="col-auto">
			<h2 class="mb-2">Product details</h2>
		</div>
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-name">Product Name</label>
		<input class="form-control" name="name" maxlength="200"  id="id_name" type="text" value="{{ product.name|default_if_none:'' }}" placeholder="Product name"  disabled/>
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-gender">Category</label>
		<select class="form-select" name="category"  id="id_category" aria-label="Default select example" disabled>
			<option selected="selected">{{ product.category }}</option>
		</select>
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-password">Price</label>
		<input class="form-control" name="price" step="0.01"  id="id_price" type="number" value="{{ product.price|default_if_none:'' }}" placeholder="$"  disabled/>
	</div>
	<div class="mb-3">
		<label class="form-label">Product Image</label>
		<br>
		<br>
		<img src="{{ product.image.url }}" alt="" width="400" height="200" disabled>
	</div>
	<div class="mb-3">
		<label class="form-label" for="basic-form-textarea">Description</label>
		<textarea class="form-control" name="description" id="basic-form-textarea" rows="5" cols="40" placeholder="Description" disabled>{{ product.description|default_if_none:'' }}</textarea>
	</div>
	<div class="mb-3 form-check">
		<input class="form-check-input" name="published" id="id_published" {% if product.published %}checked{% endif %} type="checkbox"  disabled/>
	</div>
	<div class="col-auto">
		<a class="btn btn-warning me-2 mb-2 mb-sm-0" href="{% url 'products-list-admin' %}">Cancel</a>
		<a class="btn btn-primary me-2 mb-2 mb-sm-0" href="{% url 'edit_product' product.id %}">Edit</a>
	</div>
{% endblock %}